# XML example and exercise
****
+ study examples of accessing nodes in XML tree structure  
+ work on exercise to be completed and submitted
****
+ reference: https://docs.python.org/2.7/library/xml.etree.elementtree.html
+ data source: http://www.dbis.informatik.uni-goettingen.de/Mondial
****

In [1]:
from xml.etree import ElementTree as ET

## XML example

+ for details about tree traversal and iterators, see https://docs.python.org/2.7/library/xml.etree.elementtree.html

In [3]:
document_tree = ET.parse( './data/mondial_database_less.xml' )

In [4]:
# print names of all countries
for child in document_tree.getroot():
    print child.find('name').text

Albania
Greece
Macedonia
Serbia
Montenegro
Kosovo
Andorra

In [5]:
# print names of all countries and their cities
for element in document_tree.iterfind('country'):
    print '* ' + element.find('name').text + ':',
    capitals_string = ''
    for subelement in element.getiterator('city'):
        capitals_string += subelement.find('name').text + ', '
    print capitals_string[:-2]

* Albania: Tirana, Shkodër, Durrës, Vlorë, Elbasan, Korçë
* Greece: Komotini, Kavala, Athina, Peiraias, Peristeri, Acharnes, Patra, Kozani, Kerkyra, Ioannina, Thessaloniki, Iraklio, Chania, Ermoupoli, Rhodes, Tripoli, Lamia, Chalkida, Larissa, Volos, Mytilini, Karyes
* Macedonia: Skopje, Kumanovo
* Serbia: Beograd, Novi Sad, Niš
* Montenegro: Podgorica
* Kosovo: Prishtine
* Andorra: Andorra la Vella

# ================================================
****
## XML exercise

Using data in 'data/mondial_database.xml', the examples above, and refering to https://docs.python.org/2.7/library/xml.etree.elementtree.html, find

1. 10 countries with the lowest infant mortality rates
2. 10 cities with the largest population
3. 10 ethnic groups with the largest overall populations (sum of best/latest estimates over all countries)
4. name and country of a) longest river, b) largest lake and c) airport at highest elevation

# ================================================

# Import Pandas and XML ElementTree

In [3]:
from xml.etree import ElementTree as ET
import pandas as pd

# Parse XML file

In [4]:
document_tree = ET.parse( './data/mondial_database.xml' )

In [5]:
def calculatePopulation(row):
    if row.top_ethnicity:
        return (float(row.ethnic_perc) / 100) * int(row.recent_population)
    else:
        return None

In [6]:
country_list = []
country_codes = []
mort_rates = []
pops = []
ethnicities = []
ethnic_percent = []

columns = ['name', 'country_code', 'infant_mortality', 'recent_population', 'top_ethnicity', 'ethnic_perc', 'ethnic_pop', 'longest_river', 'river_length', 'biggest_lake', 'lake_area', 'highest_airport', 'airport_elevation']

for element in document_tree.iterfind('country'):
    # For each country element get the name, country code, and infant mortality rate
    country_list.append(element.find('name').text)
    country_codes.append(element.attrib['car_code'])
    try:
        mort_rates.append(element.find('infant_mortality').text)
    except:
        mort_rates.append(None)
        
    # Create sorted list comprehension of dictionaries for top level population elements under 'country'
    pop_dict_list = [{'year': subel.attrib['year'], 'value': subel.text} for subel in element.iterfind('population')]
        
    newlist = sorted(pop_dict_list, key=lambda k: k['year'])[-1:]
    
    # This will append the most recent population recorded to the list
    pops.append(newlist[0]['value'])        
    
    # Create sorted list comprehension of dictionaries for ethnic group elements under 'country'
    ethnic_dict_list = [{'percent': subel.attrib['percentage'], 'value': subel.text} for subel in element.iterfind('ethnicgroup')]
        
    newlist = sorted(ethnic_dict_list, key=lambda k: k['percent'])[-1:]
    
    if len(newlist) > 0:
        ethnicities.append(newlist[0]['value'])  
        ethnic_percent.append(newlist[0]['percent'])
    else:
        ethnicities.append(None)
        ethnic_percent.append(None)
        
# Create Pandas dataframe with given information extracted from XML file.
country_df = pd.DataFrame(columns=columns)
country_df['name'] = country_list
country_df['country_code'] = country_codes
country_df['infant_mortality'] = mort_rates
country_df['recent_population'] = pops
country_df['top_ethnicity'] = ethnicities
country_df['ethnic_perc'] = ethnic_percent
country_df['ethnic_pop'] = country_df.apply(lambda x: calculatePopulation(x), axis=1)

In [13]:
def findGreatestValueOfElement(target_el, comparison_var, col_name, col_name_two):
    # target_el = 'airport', 'lake', 'river'
    # comparison_var = 'elevation', 'area'
        
    element_dict = {}
    biggest_element = []
    element_max_value = []
    element_countries = []
    
    for element in document_tree.iterfind(target_el):        
        element_country = element.attrib['country'].split(' ')
        for country in element_country:
            
            # Add country values to element_countries ['Albania', 'Russia', 'Georgia']
            if country not in element_countries:
                element_countries.append(country)
                                    
            # Add [{'comp_var': 3452, 'name': 'amazon river'}] or [{'comp_var: 0': ''}] if it 
            # does not exist.
            if country not in element_dict:
                if element.find(comparison_var) is None or element.find(comparison_var).text == None:
                    element_dict[country] = [{'comp_var': 0, 'name': element.find('name').text}]
                else:
                    element_dict[country] = [{'comp_var': element.find(comparison_var).text, 'name': element.find('name').text}]
            else:
                # append to the list [{'comp_var': 3452, 'name': 'amazon river'}, {'comp_var': 284, 'random river'}]
                # because a country can have multiple airports/rivers/lakes
                
                if element.find(comparison_var) is None or element.find(comparison_var).text == None:
                    element_dict[country].append({'comp_var': 0, 'name': element.find('name').text})
                else:
                    element_dict[country].append({'comp_var': element.find(comparison_var).text, 'name': element.find('name').text})
                
    # this takes care of any countries that don't have the comparison variable. so it matches 
    # the list length of the original countries dataset when appending the biggest element column.
    for code in country_df['country_code'].tolist():
        if code not in element_dict:
            element_dict[code] = [{'comp_var': 0, 'name': 'NA'}]
    
    # sort all the lists so the comparison variable of type int or float is on top.
    for item in element_dict:
        try:
            element_dict[item] = sorted(element_dict[item], key=lambda k: int(k['comp_var']))[-1:]
        except:
            element_dict[item] = sorted(element_dict[item], key=lambda k: float(k['comp_var']))[-1:]
            
        # remove all other objects, and turn item into one dictionary rather than a list.
        element_dict[item] = element_dict[item][0]
        biggest_element.append(element_dict[item]['name'])
        element_max_value.append(element_dict[item]['comp_var'])

    country_df[col_name] = biggest_element
    country_df[col_name_two] = element_max_value

In [14]:
findGreatestValueOfElement('airport', 'elevation', 'highest_airport', 'airport_elevation')
findGreatestValueOfElement('river', 'length', 'longest_river', 'river_length')
findGreatestValueOfElement('lake', 'area', 'biggest_lake', 'lake_area')

In [18]:
def findTopValue(df, column_measurement):
    try:
        df[column_measurement] = df[column_measurement].astype('int')
    except:
        df[column_measurement] = df[column_measurement].astype('float')
        
    max_value = df.sort_values(by=column_measurement, ascending=False).head(1)
    return max_value

In [19]:
findTopValue(country_df, 'airport_elevation')

,name,country_code,infant_mortality,recent_population,top_ethnicity,ethnic_perc,ethnic_pop,longest_river,river_length,biggest_lake,lake_area,highest_airport,airport_elevation
23,Russia,R,7.08,143666931,Russian,79.8,1.146462e+08,Elbe,1091,Lake Genezareth,165,El Alto Intl,4063

In [20]:
findTopValue(country_df, 'river_length')

,name,country_code,infant_mortality,recent_population,top_ethnicity,ethnic_perc,ethnic_pop,longest_river,river_length,biggest_lake,lake_area,highest_airport,airport_elevation
72,Thailand,THA,9.86,65981659,Thai,75,49486244.25,Amazonas,6448,NA,0,Bellegarde,396

In [21]:
findTopValue(country_df, 'lake_area')

,name,country_code,infant_mortality,recent_population,top_ethnicity,ethnic_perc,ethnic_pop,longest_river,river_length,biggest_lake,lake_area,highest_airport,airport_elevation
17,Switzerland,CH,3.73,8139631,German,65,5290760.15,Donau,2845,Caspian Sea,386400.0,Minsk 2,204

In [22]:
country_df

,name,country_code,infant_mortality,recent_population,top_ethnicity,ethnic_perc,ethnic_pop,longest_river,river_length,biggest_lake,lake_area,highest_airport,airport_elevation
0,Albania,AL,13.19,2800138,Albanian,95,2.660131e+06,Thjorsa,230,Saimaa,4370.0,Kabul Intl,1792
1,Greece,GR,4.78,10816286,Greek,93,1.005915e+07,Glomma,604,Mjoesa-See,368.0,Tirana Rinas,38
2,Macedonia,MK,7.9,2059794,Macedonian,64.2,1.322388e+06,Dalaelv,520,Vaenern,5648.0,Tamanrasset,1377
3,Serbia,SRB,6.16,7120666,Serb,82.9,5.903032e+06,Kemijoki,550,Arresoe,40.2,Pago Pago Intl,10
4,Montenegro,MNE,None,620029,Bosniak,8,4.960232e+04,Lena,4400,Loch Lomond,71.0,Lubango,1762
5,Kosovo,KOS,None,1733872,Albanian,92,1.595162e+06,Thames,346,Bodensee,538.5,Wallblake,39
6,Andorra,AND,3.69,78115,African,5,3.905750e+03,Rhein,1324,Bodensee,538.5,V C Bird Intl,19
7,France,F,3.31,64933400,None,None,NaN,Maas,925,Lac Leman,581.0,Salta,1246
8,Spain,E,3.33,46815916,Mediterranean Nordic,100,4.681592e+07,Rhein,1324,Lac Leman,581.0,Zvartnots,865
9,Austria,A,4.16,8499759,Austrian,91.1,7.743280e+06,Tajo,1007,Lago di Garda,370.0,Reina Beatrix Intl,18
10,Czech Republic,CZ,2.63,10562214,Czech,90.4,9.548241e+06,Rhein,1324,Laguna de Gallocanta,14.4,Canberra,575
11,Germany,D,3.46,80219695,German,91.5,7.340102e+07,Tajo,1007,Balaton,594.0,Innsbruck,581
12,Hungary,H,5.09,9937628,Hungarian,92.3,9.172431e+06,Drau,749,Lake Skutari,368.0,Heydar Aliyev,3
13,Italy,I,3.31,59433744,None,None,NaN,Donau,2845,Lake Skutari,368.0,Lynden Pindling Intl,5
14,Liechtenstein,FL,4.33,36636,Alemannic,95,3.480420e+04,Donau,2845,Lake Ohrid,367.0,Bahrain Intl,2
15,Slovakia,SK,5.35,5397036,Hungarian,9.7,5.235125e+05,Donau,2845,Lake Prespa,273.0,Zia Intl,9
16,Slovenia,SLO,4.04,2058821,Slovene,91,1.873527e+06,Donau,2845,Kremenchuk Reservoir,2252.0,Grantley Adams Intl,52
17,Switzerland,CH,3.73,8139631,German,65,5.290760e+06,Donau,2845,Caspian Sea,386400.0,Minsk 2,204
18,Belarus,BY,3.64,9460692,Belorussian,81.2,7.682082e+06,Donau,2845,Ozero Pskovskoje,3555.0,Aéroport de Liège,201
19,Latvia,LV,7.91,2201196,Latvian,59.3,1.305309e+06,Donau,2845,Lop Nor,5000.0,Philip S W Goldson Intl,5
20,Lithuania,LT,6,2979310,Lithuanian,84,2.502620e+06,Donau,2845,Dead Sea,41650.0,Cadjehoun,6
21,Poland,PL,6.19,38533789,Polish,97.6,3.760898e+07,Donau,2845,Dead Sea,41650.0,Bermuda Intl,4
22,Ukraine,UA,8.1,45633637,Ukrainian,77.8,3.550297e+07,Donau,2845,Dead Sea,41650.0,Paro,2235
23,Russia,R,7.08,143666931,Russian,79.8,1.146462e+08,Elbe,1091,Lake Genezareth,165.0,El Alto Intl,4063
24,Belgium,B,4.18,11099554,Fleming,58,6.437741e+06,Save,945,Lake Van,3740.0,Sarajevo,521
25,Luxembourg,L,4.28,524853,Luxembourgish,63.1,3.311822e+05,Save,945,Caspian Sea,386400.0,Sir Seretse Khama Intl,1006
26,Netherlands,NL,3.66,16843181,Dutch,80.7,1.359245e+07,Tara,140,Caspian Sea,386400.0,Presidente Juscelino Kubitschek,1061
27,Bosnia and Herzegovina,BIH,5.84,3791622,Muslim,48,1.819979e+06,Southern Morava,295,Caspian Sea,386400.0,Terrance B Lettsome Intl,5
28,Croatia,HR,5.87,4290612,Croat,89.6,3.844388e+06,Southern Morava,295,Caspian Sea,386400.0,Brunei Intl,22
29,Bulgaria,BG,15.08,7284552,Turkish,8,5.827642e+05,Rhein,1324,Ozero Aral,17160.0,Sofia,531
...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,Chad,TCH,90.3,11720781,None,None,NaN,NA,0,NA,0.0,Providenciales,5
215,Equatorial Guinea,GQ,71.12,696167,None,None,NaN,NA,0,NA,0.0,Funafuti International,3
216,Gabon,G,47.03,1556222,None,None,NaN,NA,0,NA,0.0,Entebbe Intl,1153
217,Cape Verde,CV,24.28,491875,Creole,71,3.492312e+05,NA,0,NA,0.0,Lviv Intl,327
218,Sudan,SUD,52.86,35652002,Arab,70,2.495640e+07,NA,0,NA,0.0,Al Ain International Airport,265
219,South Sudan,SSD,68.16,8260490,None,None,NaN,NA,0,NA,0.0,Leeds Bradford,208
220,Comoros,COM,65.31,683081,None,None,NaN,NA,0,NA,0.0,Santa Fe Muni,1935
221,Guinea,RG,55.24,10628972,Peuhl,40,4.251589e+06,NA,0,NA,0.0,Carrasco Intl,32
222,Liberia,LB,69.19,3957990,African,95,3.760090e+06,NA,0,NA,0.0,Samarkand,678
223,Djibouti,DJI,50.2,834036,Somali,60,5.004216e+05,NA,0,NA,0.0,Port Vila Bauerfield,21
224,Eritrea,ER,38.44,5741159,Tigrinya,55,3.157637e+06,NA,0,NA,0.0,Barquisimeto Intl,623
225,Ethiopia,ETH,55.77,84320987,Somali,6.2,5.227901e+06,NA,0,NA,0.0,Noibai Intl,12
226,Somalia,SP,100.14,9636173,Somali,85,8.190747e+06,NA,0,NA,0.0,Cyril E King,7
227,Kenya,EAK,40.71,40909194,Meru,6,2.454552e+06,NA,0,NA,0.0,Wallis,24
228,Gambia,WAG,65.74,1882450,African,99,1.863626e+06,NA,0,NA,0.0,Hassan I Airport,63
229,Senegal,SN,52.72,13508715,Toucouleur,9,1.215784e+06,NA,0,NA,0.0,Sanaa Intl,2200
230,Guinea-Bissau,GNB,90.92,1586624,African,99,1.570758e+06,NA,0,NA,0.0,Ndola,1270
231,Sierra Leone,WAL,73.29,5751976,African,99,5.694456e+06,NA,0,NA,0.0,Harare Intl,1490
232,Uganda,EAU,60.82,34856813,Iteso,8,2.788545e+06,NA,0,NA,0.0,NA,0
233,Lesotho,LS,50.48,2008921,Sotho,99.7,2.002894e+06,NA,0,NA,0.0,NA,0
234,Madagascar,RM,44.88,21842167,None,None,NaN,NA,0,NA,0.0,NA,0
235,Malawi,MW,48.01,15013694,None,None,NaN,NA,0,NA,0.0,NA,0
236,Mozambique,MOC,72.42,23700715,Euro-African,0.2,4.740143e+04,NA,0,NA,0.0,NA,0
237,Mauritius,MS,10.59,1237091,Indo-Mauritian,68,8.412219e+05,NA,0,NA,0.0,NA,0
238,Mayotte,MAYO,56.29,212645,None,None,NaN,NA,0,NA,0.0,NA,0
239,Swaziland,SD,54.82,1193148,African,97,1.157354e+06,NA,0,NA,0.0,NA,0
240,Reunion,REUN,7.5,828581,None,None,NaN,NA,0,NA,0.0,NA,0
241,Saint Helena,HELX,17.63,5663,African descent,50,2.831500e+03,NA,0,NA,0.0,NA,0
242,Sao Tome and Principe,STP,49.16,187356,European,100,1.873560e+05,NA,0,NA,0.0,NA,0
243,Seychelles,SY,10.77,90945,Seychellois,100,9.094500e+04,NA,0,NA,0.0,NA,0